LOCK TABLES `MAP_STATE_TB` WRITE;
/*!40000 ALTER TABLE `MAP_STATE_TB` DISABLE KEYS */;

INSERT INTO `MAP_STATE_TB` (`state`, `stateCode`)
VALUES
	('AdminDelete',1),
	('Delete',2),
	('Temp',3),
	('Service',4);

/*!40000 ALTER TABLE `MAP_STATE_TB` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `MAP_USER_STATE_TB` WRITE;
/*!40000 ALTER TABLE `MAP_USER_STATE_TB` DISABLE KEYS */;

INSERT INTO `MAP_USER_STATE_TB` (`userState`, `userStateCode`)
VALUES
	('Leave',1),
	('deactivate',2),
	('active',3);

/*!40000 ALTER TABLE `MAP_USER_STATE_TB` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `MAP_PROCESS_TB` WRITE;
/*!40000 ALTER TABLE `MAP_PROCESS_TB` DISABLE KEYS */;

INSERT INTO `MAP_PROCESS_TB` (`process`, `processCode`)
VALUES
	('processed',1),
	('passed',2),
	('newest',3);

/*!40000 ALTER TABLE `MAP_PROCESS_TB` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `MAP_POWER_TB` WRITE;
/*!40000 ALTER TABLE `MAP_POWER_TB` DISABLE KEYS */;

INSERT INTO `MAP_POWER_TB` (`power`, `powerCode`)
VALUES
	('admin',1),
	('manager',2),
	('user',3);

/*!40000 ALTER TABLE `MAP_POWER_TB` ENABLE KEYS */;
UNLOCK TABLES;
